### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by EyalMichaeli** [Westlake-AI/openmixup#53] opened 2023-09-09 10:54 UTC
Hello,

I want to reproduce the **exact** results on the AirCraft dataset, as appears [here](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/aircrafts). 
I assume:

-  I need to use the [config generator](https://github.com/Westlake-AI/openmixup/blob/main/configs/classification/aircrafts/mixups/auto_train_mixups.py).
-  The alpha should be taken from [Mixup_Downstreams](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/mixup_benchmarks/Mixup_downstream.md) (I.e. using alpha = 2 for AirCraft, SAMix)
- I should use --deterministic flag

To conclude, the generation function vars should be:
```python
    # *** mixups ***
    base_path = "configs/classification/aircrafts/mixups/basic/r18_mixups_CE_none.py"
    # base_path = "configs/classification/aircrafts/mixups/basic/rx50_mixups_CE_none.py"
åç
    # abbreviation of long attributes
    abbs = {
        'max_epochs': 'ep'
    }
    # create nested dirs (cannot be none)
    model_var = {
        'model.mix_mode': ["vanilla"],
        # 'model.mix_mode': ["vanilla", "mixup", "cutmix", "manifoldmix", "fmix", "saliencymix", "resizemix", "puzzlemix",],
    }
    # adjust sub-attributes (cannot be none)
    gm_var = {
        'model.alpha': [0],  # default: 0.2
        'runner.max_epochs': [200,],
    }
```

Questions:

1. Is what I assumed till now, right? 
2. In [Mixup_Downstreams](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/mixup_benchmarks/Mixup_downstream.md) there is a note: _"Please refer to config files for experiment details: [CUB-200](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/cub200/mixups/basic) and [FGVC-Aircraft](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/aircrafts/mixups/basic). As for config files of various mixups, please modify **max_epochs** and mix_mode in auto_train_mixups.py to generate configs and bash scripts."_
**Why would I change max_epochs if (another quote):**
_"These benchmarks follow transfer learning settings on fine-grained datasets, using PyTorch official pre-trained models as initialization and **training 200 epochs** on [CUB-200](http://www.vision.caltech.edu/visipedia/CUB-200-2011.html) and [FGVC-Aircraft](https://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft/)."_
Just making sure that using 200 epochs is the way to go.

**3. The only missing part for me to be able to reproduce is what seeds and batch size you guys use in your experiments?**

4. batch size explanation: In get_started.md it's pointed out that we should scale the LR according to the num GPUs originally used (4/8), how can I know the num of GPUs used? it's not written. For now, I sent 2 runs where I actually use one GPU and just increased the batch size to 64 and 128 (original was 16). Would love to know what was used.
5. I saw that SAMix is no implemented yet. when will it be?

Sorry if it's a bit too much of a small-scale problem. I just want to make sure to reproduce the results exactly since this is for an important project.

Thank you very much for the great repo!

**Comment by Lupin1998** [comment] 2023-09-10 20:34
Hello, @EyalMichaeli, thanks for using OpenMixup to reproduce FGVC-Aircraft results. I will answer your questions point-by-point:
1. What you have assumed is right. You can generate the config file by the [config generator](https://github.com/Westlake-AI/openmixup/blob/main/configs/classification/aircrafts/mixups/auto_train_mixups.py) to modify `alpha` and `mix_mode` according to [Mixup downstream](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/mixup_benchmarks/Mixup_downstream.md). The `--deterministic` might not be necessary if you run the experiment for many trials.
2. In [AutoMix](https://arxiv.org/abs/2103.13027) and OpenMixup benchmark, we fine-tune 200 epochs for CUB-200 and FGVC-Aircraft. Since we adopted a cosine scheduler, you can also run experiments of custom training epochs (e.g., 100 epochs).
3. According to the config files in [aircrafts/mixups](https://github.com/Westlake-AI/openmixup/blob/main/configs/classification/aircrafts), the basic setting includes an SGD optimizer (lr=0.001, momentum=0.9, weight_decay=0.0005), a batch size of 16, and the cosine scheduler (min_lr=0). The random seed is defaulted to 0 in all our experiments.
4. The batch size and the GPU number should obey the linear scaling rule proposed by Kaiming He. The default setting is the batch size of 16 with a single GPU. If you try to train with 2 GPUs, you should change `imgs_per_gpu=16` to `imgs_per_gpu=8` in the config file since all arguments in the config file are started for each GPU. Meanwhile, the fine-tuning settings of fine-grained classification tasks usually choose a small batch size (e.g., 8, 16, or 32), and a large batch size will result in bad performance.
5. You can adopt the config settings in [cub200/mixups](https://github.com/Westlake-AI/openmixup/blob/main/configs/classification/cub200) for [AutoMix](https://arxiv.org/abs/2103.13027) and [SAMix](https://arxiv.org/abs/2111.15454), by changing the dataset setting and `num_classes`. We will also update these config files as soon as possible.

I hope these will be helpful to you. Please feel free to make comments if there are more questions.

**Comment by EyalMichaeli** [comment] 2023-09-13 22:27
Thanks for the informative reply!
I tried running SAMix and rann into a NotImplementedError:
`Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 200, in main
    train_model(
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/apis/train.py", line 225, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/models/classifiers/base_model.py", line 197, in train_step
    losses = self(**data)
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/models/classifiers/base_model.py", line 119, in forward
    return self.forward_train(img, **kwargs)
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/models/classifiers/mixup_classification.py", line 384, in forward_train
    losses, cur_idx = self.forward_mix(img.clone(), gt_label, remove_idx=remove_idx)
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/models/classifiers/mixup_classification.py", line 295, in forward_mix
    img = self._mixblock()
  File "/mnt/raid/home/eyal_michaeli/anaconda3/envs/openmixup/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/raid/home/eyal_michaeli/git/openmixup/openmixup/models/classifiers/mixup_classification.py", line 225, in _mixblock
    raise NotImplementedError
NotImplementedError`

Tried 
base_path = "configs/classification/aircrafts/samix/r18_l2_a2_bili_val_dp01_mb_mlr5e_4_1xb16_ep200.py"
(after I copied the configs from cub200 to aircraft) 
for auto_train_mixups script.

What did I do wrong?

**Comment by Lupin1998** [comment] 2023-09-14 00:28
Hi, @EyalMichaeli, I should copy and modify the config file from `configs/classification/cub200/automix` and `configs/classification/cub200/samix` to run experiments of AutoMix and SAMix on FGVC-Aircrafts, since we haven't open-sourced the pre-trained implementations of AutoMix and SAMix in `openmixup/models/classifiers/mixup_classification.py`. I attached the config files of AutoMix and SAMix for FGVC-Aircrafts below, and you can place them under `configs/classification/aircrafts` to train SAMix, [configs/classification/aircrafts.zip](https://github.com/Westlake-AI/openmixup/files/12602696/configs_classification_aircrafts.zip). Some hyper-parameters like `min_lr` might be tuned to get better performance.

**Comment by Lupin1998** [comment] 2023-10-02 22:42
Thanks for your questions and for using OpenMixup! I will close this issue if there are no more questions.

**Closed by Lupin1998** 2023-10-02 22:42 UTC
Labels: help wanted
